In [4]:
# numpy 호출
import numpy as np

# 배열 생성, 하나의 데이터 type만 배열에 넣을 수 있다.
test_array = np.array([1,4,5,8],float)
print(test_array)
print(type(test_array[3]))

[1. 4. 5. 8.]
<class 'numpy.float64'>


In [5]:
test_array = np.array([1, 4, 5, "8"], float) 
# String Type test_array

print(type(test_array[3])) # Float Type

<class 'numpy.float64'>


In [7]:
print(test_array.dtype)

float64


In [8]:
print(test_array)

[1. 4. 5. 8.]


In [15]:
# 1차원 vector
vector = [1,2,3,4]
print(np.array(vector, int).shape)
print()

# 2차원 matrix
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
print(np.array(matrix, int).shape)
print()

# 3차원 tensor
tensor =[[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
        [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
print(np.array(tensor, int).shape)
print(np.array(tensor, int).ndim)
# size = 4*3*4
print(np.array(tensor, int).size)

(4,)

(3, 4)

(4, 3, 4)
3
48


In [27]:
a = np.array([[1,2,3],[4.5,5,6]], dtype=int)

print(a)

print(np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32))

print()
# int는 32byte
print(np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32).nbytes)

print(np.array([[1,2,3],[4.5,"5","6"]], dtype=np.int8).nbytes)

print(np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float64).nbytes)


[[1 2 3]
 [4 5 6]]
[[1.  2.  3. ]
 [4.5 5.  6. ]]

24
6
48
