In [1]:
import numpy as np

In [4]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
print(test_array > 3)

# 3보다 큰 값들을 list에 출력
print()
print(test_array[test_array > 3])

print()
condition = test_array <3
print(test_array[condition])

[False  True False False False  True  True  True]

[4. 8. 9. 7.]

[1. 0. 2.]


In [8]:
 A = np.array([ 
     [12, 13, 14, 12, 16, 14, 11, 10, 9], 
     [11, 14, 12, 15, 15, 16, 10, 12, 11], 
     [10, 12, 12, 15, 14, 16, 10, 12, 12], 
     [ 9, 11, 16, 15, 14, 16, 15, 12, 10], 
     [12, 11, 16, 14, 10, 12, 16, 12, 13], 
     [10, 15, 16, 14, 14, 14, 16, 15, 12], 
     [13, 17, 14, 10, 14, 11, 14, 15, 10],
     [10, 16, 12, 14, 11, 12, 14, 18, 11], 
     [10, 19, 12, 14, 11, 12, 14, 18, 10], 
     [14, 22, 17, 19, 16, 17, 18, 17, 13], 
     [10, 16, 12, 14, 11, 12, 14, 18, 11], 
     [10, 16, 12, 14, 11, 12, 14, 18, 11], 
     [10, 19, 12, 14, 11, 12, 14, 18, 10], 
     [14, 22, 12, 14, 11, 12, 14, 17, 13], 
     [10, 16, 12, 14, 11, 12, 14, 18, 11]])
    
B = A<15
print(B)

print()

print(B.astype(np.int))

[[ True  True  True  True False  True  True  True  True]
 [ True  True  True False False False  True  True  True]
 [ True  True  True False  True False  True  True  True]
 [ True  True False False  True False False  True  True]
 [ True  True False  True  True  True False  True  True]
 [ True False False  True  True  True False False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False False False False False False False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]]

[[1 1 1 1 0 1 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 1 0 1 1 1]
 [1 1 0 0 1 0 0 1 1]
 [1 1 0 1 1 1 0 1 1]
 [1 0 0 1 1 1 0 0 1]
 [1 0 1 1 1 1 1 0

In [20]:
a = np.array([2,4,6,8], float)
print(a[a>4])

print()
a.take(b) # take : bracket index

a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)

print(a)
print()

# b row index, c column index
print(a[b,c])
print()
print(a[b])

[6. 8.]

[[ 1.  4.]
 [ 9. 16.]]

[ 1.  4. 16. 16.  4.]

[[ 1.  4.]
 [ 1.  4.]
 [ 9. 16.]
 [ 9. 16.]
 [ 1.  4.]]
